# Generated by Django 5.2.3 on 2025-06-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="verb",
            field=models.CharField(default="hunt", max_length=20),
        ),
        migrations.AlterField(
            model_name="task",
            name="character_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="planet_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="ship_name",
            field=models.CharField(max_length=255),
        ),
    ]
